ERRORS:thub.com/aws/aws-sdk-go/aws/ec2metadata ./forms.go:110:41: s.context.messageClient.MessageDecrypt undefined (type encryptionpb.MessageServiceClient has no field or method MessageDecrypt) ./forms.go:132:72: cannot use s.context (type *serverContext) as type context.Context in argument to s.context.messageClient.GenerateRandomString:         *serverContext does not implement context.Context (missing Deadline method) ./forms.go:153:65: cannot use s.context (type *serverContext) as type context.Context in argument to s.context.messageClient.EncryptMessage:         *serverContext does not implement context.Context (missing Deadline method) ./forms.go:153:103: unknown field 'plainText' in struct literal of type encryptionpb.EncryptedMessageRequest (but does have PlainText) ./forms.go:153:128: cannot use encryptionbytes (type *encryptionpb.Randomresponse) as type []byte in field value ./forms.go:162:80: undefined: encryptionstring ./forms.go:180:16: msg.Deliver undefined (type *message.MessagePost has no field or method Deliver) github.com/aws/aws-sdk-go/private/protocol/json/jsonutil